import { AudioSfz, AudioSfzVariables } from '../types/audio';
import FileLoader from './fileLoader';
declare function parseSfz(prefix: string, contents: string): Promise<any>;
declare function processDirective(input: string): RegExpMatchArray | [];
declare function processHeader(input: string): RegExpMatchArray | [];
declare function processOpcode(input: string): any;
declare function processVariables(input: string, vars: AudioSfzVariables): string;
declare function flattenSfzObject(sfzObject: AudioSfz): any;
declare function setParserLoader(fileLoader: FileLoader): void;
export { flattenSfzObject, parseSfz, processDirective, processHeader, processOpcode, processVariables, setParserLoader, };
